### ISSUE TITLE
undefined method `include' for #<ActionCable::Server::Configuration:0x007fde92e726d8> 

### ISSUE THREAD

**Issue by xanview** [rocketjob/rails_semantic_logger#10]
It seems rails_semantic_logger won't work on Rails 5.0 beta, I am getting the following:

```
[79942] ! Unable to load application: NoMethodError: undefined method `include' for #<ActionCable::Server::Configuration:0x007fde92e726d8>
/usr/local/lib/ruby/gems/2.3.0/gems/rails_semantic_logger-3.0.0/lib/rails_semantic_logger/railtie.rb:71:in `block (3 levels) in <class:Railtie>': undefined method `include' for #<ActionCable::Server::Configuration:0x007fde92e726d8> (NoMethodError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /usr/local/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/server/base.rb:72:in `<module:Server>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/server/base.rb:4:in `<module:ActionCable>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/server/base.rb:3:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `block in require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:268:in `load_dependency'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/dependencies.rb:302:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable.rb:43:in `server'
	from cable/config.ru:4:in `block in <main>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in `instance_eval'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in `initialize'
	from cable/config.ru:in `new'
	from cable/config.ru:in `<main>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:49:in `eval'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:49:in `new_from_string'
	from /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:40:in `parse_file'
	from /usr/local/lib/ruby/gems/2.3.0/gems/puma-2.16.0/lib/puma/configuration.rb:155:in `load_rackup'
	from /usr/local/lib/ruby/gems/2.3.0/gems/puma-2.16.0/lib/puma/configuration.rb:99:in `app'
	from /usr/local/lib/ruby/gems/2.3.0/gems/puma-2.16.0/lib/puma/runner.rb:114:in `load_and_bind'
	from /usr/local/lib/ruby/gems/2.3.0/gems/puma-2.16.0/lib/puma/cluster.rb:318:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/puma-2.16.0/lib/puma/cli.rb:214:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/puma-2.16.0/bin/puma:10:in `<top (required)>'
	from /usr/local/bin/puma:23:in `load'
	from /usr/local/bin/puma:23:in `<main>'
```

Any suggestions?

**Comment by reidmorrison** [comment]
Please update rails_semantic_logger gem to the latest `3.0.1` and re-open this ticket if it does not work.

**Comment by xanview** [comment]
Unfortunately doesn't work :( - the Rails app starts (with a warning) and then dies with an exception.

The warning:

```
$ bundle exec puma -p 28080 cable/config.ru
[59197] Puma starting in cluster mode...
[59197] * Version 2.16.0 (ruby 2.3.0-p0), codename: Midwinter Nights Trance
[59197] * Min threads: 32, max threads: 32
[59197] * Environment: development
[59197] * Process workers: 5
[59197] * Preloading application
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <class:Connection> at /usr/local/lib/ruby/gems/2.3.0/bundler/gems/rack-mini-profiler-973971f511f5/lib/patches/db/mongo.rb:11)
[59197] * Listening on tcp://0.0.0.0:28080
[59197] * Listening on tcp://0.0.0.0:3000
[59197] ! WARNING: Detected 1 Thread(s) started in app boot:
[59197] ! #<Thread:0x007f83194681d0@/usr/local/lib/ruby/gems/2.3.0/gems/semantic_logger-3.0.1/lib/semantic_logger/logger.rb:143 sleep> - /usr/local/lib/ruby/gems/2.3.0/gems/semantic_logger-3.0.1/lib/semantic_logger/logger.rb:165:in `pop'
[59197] Use Ctrl-C to stop
```

The exception:

```
2016-02-14 20:56:57.988828 E [59419:70100546888780 worker.rb:37] ActionCable -- There was an exception - NoMethodError(undefined method `formatter' for #<SemanticLogger::Logger:0x007f8314fd1ee0>)
2016-02-14 20:56:57.988935 E [59419:70100546888780 worker.rb:38] ActionCable -- /usr/local/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/connection/tagged_logger_proxy.rb:21:in `tag'
/usr/local/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/connection/tagged_logger_proxy.rb:36:in `log'
/usr/local/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/connection/tagged_logger_proxy.rb:30:in `block (2 levels) in <class:TaggedLoggerProxy>'
/usr/local/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/connection/base.rb:166:in `handle_close'
/usr/local/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/server/worker.rb:34:in `block in invoke'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:750:in `_run_work_callbacks'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta2/lib/active_support/callbacks.rb:90:in `run_callbacks'
/usr/local/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/server/worker.rb:33:in `invoke'
/usr/local/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0.beta2/lib/action_cable/server/worker.rb:25:in `block in async_invoke'
/usr/local/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:333:in `run_task'
/usr/local/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:322:in `block (3 levels) in create_worker'
/usr/local/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:305:in `loop'
/usr/local/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:305:in `block (2 levels) in create_worker'
/usr/local/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:304:in `catch'
/usr/local/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.0/lib/concurrent/executor/ruby_thread_pool_executor.rb:304:in `block in create_worker'
```

**Comment by reidmorrison** [comment]
To resolve the remaining issues is going to take significant monkey patching of Rails since it has a very naive logging implementation that assumes there is only one formatter and therefore a single destination for all log information. Semantic Logger has a formatter for every destination / appender and is therefore not available at the logger level itself.

Too bad @dhh did not take my suggestion at the last Rails conference and look at Semantic Logger. This would have been a lot easier.

We can do this one of two ways:
* Does someone have a running Action Cable sample application that I can use to figure out all the monkey patching in Rails?
* Or, if you can keep applying monkey patching ideas that we can work on here, and then I can include them in Semantic Logger when complete.

To get the ball rolling can you add the following monkey patch / rails initializer and see if moves to the next issue?

This will remove the reference to `formatter`:

~~~ruby
ActionCable::Connection::TaggedLoggerProxy

module ActionCable
  module Connection
    class TaggedLoggerProxy
      def tag(logger, &block)
        current_tags = tags - logger.tags
        logger.tagged(*current_tags, &block)
      end
    end
  end
end
~~~

**Comment by reidmorrison** [comment]
I added a monkey-patch for Action Cable in git head, can you change your Gemfile entry to:

~~~ruby
gem 'rails_semantic_logger', git: 'git@github.com:rocketjob/rails_semantic_logger.git'
~~~

**Comment by xanview** [comment]
That latest from git seems to work! - Still getting this warning:

```
[84337] ! WARNING: Detected 1 Thread(s) started in app boot:
[84337] ! #<Thread:0x007faa56f15290@/usr/local/lib/ruby/gems/2.3.0/gems/semantic_logger-3.0.1/lib/semantic_logger/logger.rb:143 sleep> - /usr/local/lib/ruby/gems/2.3.0/gems/semantic_logger-3.0.1/lib/semantic_logger/logger.rb:165:in `pop'
```

But otherwise working fine!

**Comment by reidmorrison** [comment]
If logging stops under Puma, it may be due to process forking. Check out the section on Puma:
http://rocketjob.github.io/semantic_logger/forking.html

**Comment by reidmorrison** [comment]
v3.3 Gem with these fixes is now available.
