### ISSUE TITLE
Errors after upgrading to 4.1

### ISSUE THREAD

**Issue by gingerlime** [rocketjob/rails_semantic_logger#38]
### Environment

Provide at least:
* Ruby Version. 2.3.1
* Rails Version. 4.2.8
* Semantic Logger Version. 4.1
* Rails Semantic Logger Version. 4.1
* Other Application/framework names and versions (e.g. Puma, etc.). Sidekiq 4.2.10
* Rails configuration. Only need the settings related to Rails Semantic Logger and Semantic Logger.
* Full Stack Trace, if an exception is being raised.

```
2017-05-10 09:18:01.893499 ERROR [28123:13799700 log_subscriber.rb:85] Rails -- Could not log "process_action.action_controller" event. NoMethodError: undefined method `to_unsafe_h' for {"controller"=>"tasks", "action"=>"report_statsd_counts"}:Hash ["/var/local/kenhub/kenhub.d/913/vendor/bundle/ruby/2.3.0/gems/rails_semantic_logger-4.1.0/lib/rails_semantic_logger/extensions/action_controller/log_subscriber.rb:14:in `block in process_action'", "/var/local/kenhub/kenhub/vendor/bundle/ruby/2.3.0/gems/semantic_logger-4.1.0/lib/semantic_logger/log.rb:131:in `assign_positional'", "/var/local/kenhub/kenhub/vendor/bundle/ruby/2.3.0/gems/semantic_logger-4.1.0/lib/semantic_logger/base.rb:307:in `log_internal'", "/var/local/kenhub/kenhub/vendor/bundle/ruby/2.3.0/gems/semantic_logger-4.1.0/lib/semantic_logger/base.rb:84:in `info'", "/var/local/kenhub/kenhub.d/913/vendor/bundle/ruby/2.3.0/gems/rails_semantic_logger-4.1.0/lib/rails_semantic_logger/extensions/action_controller/log_subscriber.rb:12:in `process_action'", 
...
```

```
2017-05-10 09:18:10.299339 ERROR [28121:13799700 log_subscriber.rb:85] Rails -- Could not log "write_fragment.action_controller" event. NoMethodError: undefined method `enable_fragment_cache_logging' for ActionController::Base:Class ["/var/local/kenhub/kenhub.d/913/vendor/bundle/ruby/2.3.0/gems/rails_semantic_logger-4.1.0/lib/rails_semantic_logger/extensions/action_controller/log_subscriber.rb:72:in `write_fragment'", "/var/local/kenhub/kenhub/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/subscriber.rb:100:in `finish'", "/var/local/kenhub/kenhub/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/log_subscriber.rb:83:in `finish'", "/var/local/kenhub/kenhub/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications/fanout.rb:102:in `finish'", "/var/local/kenhub/kenhub/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications/fanout.rb:46:in `block in finish'", "/var/local/kenhub/kenhub/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications/fanout.rb:46:in `each'", "/var/local/kenhub/kenhub/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications/fanout.rb:46:in `finish'", "/var/local/kenhub/kenhub/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:36:in `finish'", "/var/local/kenhub/kenhub/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:25:in `instrument'", "/var/local/kenhub/kenhub/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'", "/var/local/kenhub/kenhub/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_controller/caching/fragments.rb:99:in `instrument_fragment_cache'", "/var/local/kenhub/kenhub/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_controller/caching/fragments.rb:31:in `write_fragment'", "/var…
```

configs:

```
# config/environments/production.rb
config.log_level = :info                                                                                                                                                                                                                 
config.log_errors_to_sentry = true                                                                                                                                                                                                       
config.paths['log'] = "/var/log/kenhub/#{Rails.env}.log"                                                                                                                                                                                 
config.colorize_logging = false                                                                                                                                                                                                          
config.rails_semantic_logger.quiet_assets = true
```

```
# config/initializers/logging.rb
include SemanticLogger::Loggable

# based on https://github.com/rocketjob/semantic_logger/blob/0f047df6019a14dcd2c05cac9cbfbf38f0a24461/lib/semantic_logger/formatters/default.rb
# only small modification of log level to show DEBUG/WARN instead of D/W/...
module SemanticLogger
  module Formatters
    class Kenhub < Base
      # Default text log format
      #  Generates logs of the form:
      #    2011-07-19 14:36:15.660235 D [1149:ScriptThreadProcess] Rails -- Hello World
      def call(log, logger)
        # Date & time
        message = time_format.nil? ? '' : "#{format_time(log.time)} "

        # Log level and process info
        message << "#{log.level.upcase} [#{log.process_info}]"

        # Tags
        message << ' ' << log.tags.collect { |tag| "[#{tag}]" }.join(' ') if log.tags && (log.tags.size > 0)

        # Named Tags
        if (named_tags = log.named_tags) && !named_tags.empty?
          list = []
          named_tags.each_pair { |name, value| list << "[#{name}: #{value}]" }
          message << ' ' << list.join(' ')
        end

        # Duration
        message << " (#{log.duration_human})" if log.duration

        # Class / app name
        message << " #{log.name}"

        # Log message
        message << " -- #{log.message}" if log.message

        # Payload
        if payload = log.payload_to_s
          message << ' -- ' << payload
        end

        # Exceptions
        if log.exception
          message << " -- Exception: #{log.exception.class}: #{log.exception.message}\n"
          message << log.backtrace_to_s
        end
        message
      end
    end
  end
end

if Kenhub.config.log_errors_to_sentry
  SemanticLogger.add_appender(:appender => :sentry, :level => :error)
end

unless Kenhub.config.colorize_logging
  appender = SemanticLogger.appenders.find{ |a| a.is_a?(SemanticLogger::Appender::File) }
  appender.formatter = SemanticLogger::Formatters::Kenhub.new
end

```

**Comment by reidmorrison** [comment]
Rails Semantic Logger gem v4.1.1 is now available.

**Comment by gingerlime** [comment]
:+1: works great now! Thanks @reidmorrison
